name: Cypress Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '30 14 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Make directory for uploading the test results
        run: mkdir -p mochawesome-repo

      - name: Cypress run 🧪
        uses: cypress-io/github-action@v5.1.0

      - name: Merge test results into one
        run: npm run report:merge
      - name: Generate HTML report
        run: npm run report:generate

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'